# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
u1 = User.create!(user_name: 'pepe',first_name:'pepe',last_name:'lira',address:'no tan lejos',password:'p',email:'jflira@gmail.com',phone:'9',admin:true)
u2 = User.create!(user_name: 'Cristo',first_name:'cristobal',last_name:'lara',address:'un poco mas lejos',password:'c',email:'clara@gmail.com',phone:'1',admin:false)
u3 = User.create!(user_name: 'Vito',first_name:'V',last_name:'C',address:'muy lejos',password:'v',email:'vcorleone@gmail.com',phone:'9',admin:false)
o0 = Organization.create!(name:'none',description:'none',contact:'none@none.com',location:'none')
o1 = Organization.create!(name:'Vito\'s Corp',description:'Dog food corp',contact:'contact@vcorp.com',location:'NK')
o2 = Organization.create!(name:'CIA',description:'Spy',contact:'Stan',location:'USA')
e1 = Event.create!(title:'Pizza with Dogs',description:'Vito its inviting all to eat pizza that make himself',location:'Vito\'s home',private_event:false,user_id:u1.id,organization_event:true, organization_id:o1.id, state:"On Vote")
e2 = Event.create!(title:'Juegos Diana',description:'muchos arcade para revivir la nostalgia',location:'juegos Diana Providencia',private_event:true,user_id:u2.id,organization_event:false, organization_id:o0.id, state:"Voted")
e3 = Event.create!(title:'jugar cartas',description:'muchos arcade para revivir la nostalgia',location:'casa de Pepe',private_event:true,user_id:u1.id,organization_event:false, organization_id:o0.id, state:"Closed")
of1 = OrganizationFile.create!(file_dir:'link',file_type:'Pdf',organization_id:o1.id)
of2 = OrganizationFile.create!(file_dir:'codes',file_type:'Txt',organization_id:o2.id)
i1 = Invitation.create!(acceptance:true,user_id:u1.id,event_id:e1.id)
i2 = Invitation.create!(acceptance:true,user_id:u2.id,event_id:e1.id)
i3 = Invitation.create!(acceptance:false,user_id:u3.id,event_id:e2.id)
i4 = Invitation.create!(acceptance:true,user_id:u2.id,event_id:e2.id)
m1 = Membership.create!(organization_id:o1.id,user_id:u3.id,role:'Administrador')
m2 = Membership.create!(organization_id:o1.id,user_id:u2.id,role:'Miembro')
ed1 = EventDate.create!(event_option:'20/04/1935',event_id:e1.id,final_date:true)
ed2 = EventDate.create!(event_option:'21/04/1935',event_id:e1.id,final_date:false)
ed3 = EventDate.create!(event_option:'20/04/2020',event_id:e2.id,final_date:true)
v1 = Vote.create!(invitation:i1,user_id:u1.id,event_date_id:ed1.id)
v2 = Vote.create!(invitation:i2,user_id:u2.id,event_date_id:ed2.id)
v3 = Vote.create!(invitation:i4,user_id:u2.id,event_date_id:ed3.id)
ef1 = EventFile.create!(file_dir:'link',file_type:'Pdf',event_id:e1.id)
c1 = Comment.create!(content:'?',user_id:u1.id,event_id:e1.id)
c2 = Comment.create!(content:'*',user_id:u2.id,event_id:e1.id)
c3 = Comment.create!(content:'#',user_id:u1.id,event_id:e1.id)
r1 = Reply.create!(content:'!',user_id:u1.id,comment_id:c1.id)
r1 = Reply.create!(content:'+',user_id:u1.id,comment_id:c2.id)
re1 = Report.create!(reason:'Ofensive Content',event_id:e1.id,user_id:u2.id)
me1 = Message.create!(message:'Good morning',user_id:u1.id)
n1 = Notification.create!(notification:'You have a message',notification_type:'Generic',user_id:u1.id)