# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create!([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create!(name: 'Luke', movie: movies.first)
u1 = User.create!(user_name: '1',first_name:'J',last_name:'L',address:'B',password:'p',email:'jflira@gmail.com',phone:'9',admin:true)
u2 = User.create!(user_name: '2',first_name:'C',last_name:'L',address:'C',password:'c',email:'clara@gmail.com',phone:'1',admin:false)
u3 = User.create!(user_name: '3',first_name:'V',last_name:'C',address:'M',password:'v',email:'vcorleone@gmail.com',phone:'9',admin:false)
o1 = Organization.create!(name:'I',description:'JS',contact:'SC',location:'NK')
e1 = Event.create!(title:'A',description:'R',location:'Ob',private:false,user:u1,organization_event:true)
e2 = Event.create!(title:'J',description:'P',location:'A',private:true,user:u2,organization_event:false)
of1 = OrganizationFile.create!(file_dir:'link',file_type:'Pdf',organization:o1)
i1 = Invitation.create!(acceptance:true,user:u1,event:e1)
i2 = Invitation.create!(acceptance:true,user:u2,event:e1)
i3 = Invitation.create!(acceptance:false,user:u3,event:e2)
i4 = Invitation.create!(acceptance:true,user:u2,event:e2)
m1 = Membership.create!(organization:o1,user:u1,role:'Administrador')
m2 = Membership.create!(organization:o1,user:u2,role:'Miembro')
ed1 = Eventdate.create!(event_date:'20/04/1935',event:e1)
ed2 = Eventdate.create!(event_date:'21/04/1935',event:e1)
ed3 = Eventdate.create!(event_date:'20/04/2020',event:e2)
v1 = Vote.create!(invitation:i1,user:u1,eventdate:ed1)
v2 = Vote.create!(invitation:i2,user:u2,eventdate:ed2)
v3 = Vote.create!(invitation:i4,user:u2,eventdate:ed3)
ef1 = EventFile.create!(file_dir:'link',file_type:'Pdf',event:e1)
c1 = Comment.create!(content:'?',user:u1,event:e1)
c2 = Comment.create!(content:'*',user:u2,event:e1)
c3 = Comment.create!(content:'#',user:u1,event:e1)
r1 = Reply.create!(content:'!',user:u1,comment:c1)
r1 = Reply.create!(content:'+',user:u1,comment:c2)
re1 = Report.create!(reason:'Ofensive Content',event:e1,user:u2)
me1 = Message.create!(message:'Good morning',user:u1)
n1 = Notification.create!(notification:'You have a message',notification_type:'Generic',user:u1)