# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
u1 = User.create(user_name: '1',first_name:'J',last_name:'L',address:'B',password:'p',email:'jflira@gmail.com',phone:'9',admin:true)
u2 = User.create(user_name: '2',first_name:'C',last_name:'L',address:'C',password:'c',email:'clara@gmail.com',phone:'1',admin:false)
u2 = User.create(user_name: '3',first_name:'V',last_name:'C',address:'M',password:'v',email:'vcorleone@gmail.com',phone:'9',admin:false)
o1 = Organization.create(name:'I',description:'JS',start_date:'19/04/1935 12:00',contact:'SC',location:'NK')
e1 = Event.create(title:'A',description:'R',location:'Ob',private:false,User_id:u1.id,Organization_id:o1.id)
e2 = Event.create(title:'J',description:'P',location:'A',private:true,User_id:u2.id)
of1 = OrganizationFile.create(file_dir:'link',type:'Pdf',Organization_id:o1.id)
i1 = Invitation.create(acceptance:true,User_id:u1.id,Event_id:e1.id)
i2 = Invitation.create(acceptance:true,User_id:u2.id,Event_id:e1.id)
i3 = Invitation.create(acceptance:false,User_id:u3.id,Event_id:e2.id)
i4 = Invitation.create(acceptance:true,User_id:u2.id,Event_id:e2.id)
m1 = Membership.create(Organization_id:o1.id,User_id:u1.id,role:'Administrador')
m2 = Membership.create(Organization_id:o1.id,User_id:u2.id,role:'Miembro')
ed1 = Eventdate.create(date:'20/04/1935',Event_id:e1.id)
ed2 = Eventdate.create(date:'21/04/1935',Event_id:e1.id)
ed3 = Eventdate.create(date:'20/04/2020',Event_id:e2.id)
ed4 = Eventdate.create(date:'21/04/2020',Event_id:e2.id)
v1 = Vote.create(Invitation_id:i1.id,User_id:u1.id,EventDate_id:ed1.id)
v2 = Vote.create(Invitation_id:i2.id,User_id:u2.id,EventDate_id:ed2.id)
v3 = Vote.create(Invitation_id:i4.id,User_id:u2.id,EventDate_id:ed3.id)
ef1 = EventFile.create(file_dir:'link',type:'Pdf',Event_id:e1.id)
c1 = Comment.create(content:'?',User_id:u1.id,Event_id:e1.id)
c2 = Comment.create(content:'*',User_id:u2.id,Event_id:e1.id)
c3 = Comment.create(content:'#',User_id:u1.id,Event_id:e1.id)
r1 = Reply.create(content:'!',User_id:u1.id,Comment_id:c1.id)
r1 = Reply.create(content:'+',User_id:u1.id,Comment_id:c2.id)
re1 = Report.create(reason:'Ofensive Content',Event_id:e1.id,User_id:u2.id)
me1 = Message.create(message:'Good morning',User_id:u1.id)
n1 = Notification.create(notification:'You have a message',type:'Generic',User_id:u1.id)